# Be sure to change the session secrets before deploying the app

default: &default
  app_name: "Nuts App"
  bugsnag: ''
  company_name: "Company Name"
  domain: <%= process.env.DOMAIN %>
  email:
    from_name: Nuts App
    from_email: micahlmartin@gmail.com
  google_analytics: <%= process.env.GOOGLE_ANALYTICS %>
  kue: &kue
    port: <%= parseInt(process.env.PORT, 10) %>
    name: <%= process.env.KUE_NAME %>
    concurrency: <%= process.env.KUE_CONCURRENCY %>
  layout: <%= process.env.LAYOUT || 'default' %>
  mandrill:
    api_key: <%= process.env.MANDRILL_API_KEY %>
  nodetime_key: <%= process.env.NODETIME_ACCOUNT_KEY %>
  port: <%= parseInt(process.env.PORT, 10) %>
  redis:
    env_key: <%= process.env.REDIS_ENV_KEY %>
  session: &session
    redirect_to: /login
    cookie_name: sid
    ttl_milliseconds: <%= 7 * 24 * 60 * 60 * 1000 %> # 7 days
    secret: <%= process.env.secret %>
  useSSL: true

development:
  <<: *default
  database:
    host: localhost
    port: 27017
    database: "development"
  domain: "localhost:3500"
  google_analytics: UA-56988800-1
  kue:
    <<: *kue
    port: 3800
  mandrill:
    api_key: A7LrF4jQhIzbMBiH8bU96Q
  port: 3500
  useSSL: false
  session:
    <<: *session
    secret: a17778e863b

test:
  <<: *default
  database:
    host: localhost
    port: 27017
    database: "test"
  mandrill:
    api_key: WbE5uq93hO9b0dHxvYUmMA
  session:
    <<: *session
    secret: f1dc4f56f0e

staging:
  <<: *default

production:
  <<: *default
