default: &default
  app_name: "Nuts App"
  port: <%= parseInt(process.env.PORT, 10) || 3000 %>
  hapi: {}

development:
  <<: *default
  database:
    dialect: 'sqlite'
    storage: 'tmp/development.sqlite'

staging:
  <<: *default

production:
  <<: *default
