default: &default
  app_name: "Nuts App"
  port: <%= parseInt(process.env.PORT, 10) %>
  google_analytics: <%= process.env.GOOGLE_ANALYTICS %>

development:
  <<: *default
  port: 3000
  database:
    dialect: 'sqlite'
    storage: 'tmp/development.sqlite'

staging:
  <<: *default

production:
  <<: *default
