# Be sure to change the session secrets before deploying the app

default: &default
  app_name: "Nuts App"
  company_name: "Company Name"
  domain: <%= process.env.DOMAIN %>
  email:
    from_name: Nuts App
    from_email: micahlmartin@gmail.com
  useSSL: true
  google_analytics: <%= process.env.GOOGLE_ANALYTICS %>
  mandrill:
    api_key: <%= process.env.MANDRILL_API_KEY %>
  nodetime_key: <%= process.env.NODETIME_ACCOUNT_KEY %>
  port: <%= parseInt(process.env.PORT, 10) || 3000 %>
  session: &session
    redirect_to: /login
    cookie_name: sid
    ttl_milliseconds: <%= 7 * 24 * 60 * 60 * 1000 %> # 7 days

development:
  <<: *default
  database:
    host: localhost
    port: 27017
    database: "development"
  domain: "localhost:3000"
  useSSL: false
  port: 3500
  mandrill:
    api_key: wrhAjbFY1O1JkXD2x9TKJg
  session:
    <<: *session
    secret: f1dc4f56f0e306876a17778e863b6c20f7d1d8d95ac480dca33ffb206888768474e6a44b4b4803a71322e67c599098c936243e8649d2934c2dec79b00aa281b6

staging:
  <<: *default
  session:
    <<: *session
    secret: 5fb82db1fcf7a02b13892221f094f195775ebcac9af5f8a25d53f86f269314f784121e6be9f9b2e83fe86dfdcaea6e5e395e6b9f45724b649a82fa1b1893fbe4

production:
  <<: *default
  session:
    <<: *session
    secret: b09f11c12e1939a4302556f26d32842e71dd07705da650948771db502c956dd1e3c9848a8122496f9d12e48c1eb6a9851c8f7780a1321b29ca962a9e01eec07a
