default: &default
  app_name: "Nuts App"
  port: <%= parseInt(process.env.PORT, 10) || 3000 %>
  google_analytics: <%= process.env.GOOGLE_ANALYTICS %>

development:
  <<: *default
  port: 3000
  database:
    driver: 'sqlite3'
    database_name: 'tmp/development.sqlite'

staging:
  <<: *default

production:
  <<: *default
